import React, { useState, useRef, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Search, FileText, Brain, Clock, Download, Eye, Edit3, Share2,
  Filter, Grid3x3, List, ChevronRight, X, CheckCircle, AlertTriangle,
  ArrowRight, Loader, Trash2, Zap, Shield, Lock, BookOpen, Folder,
  Plus, Send, MessageSquare, History, PenTool, Link2, Archive,
  Bell, Star, MoreHorizontal, UploadCloud, Users, Briefcase, Hash,
  TrendingUp, Info, ChevronDown, Copy, ExternalLink, RotateCcw,
  CheckSquare, ClipboardList, Gavel, FileCheck, AlertCircle, User,
  Scale, Activity, Calendar, Tag, Layers, FolderOpen, Sparkles,
  PanelRightClose, PanelRightOpen,
} from 'lucide-react';

/* ─────────────────────────────────────────────
   DESIGN TOKENS
───────────────────────────────────────────── */
const GOLD = '#D4AF37';
const GOLD_DIM = 'rgba(212,175,55,0.15)';
const DARK = '#12141f';
const DARK2 = '#1a1d2e';
const DARK3 = '#0e1019';

/* ─────────────────────────────────────────────
   MOCK DATA
───────────────────────────────────────────── */
const MOCK_DOCS = [
  {
    id: 'DOC-001',
    title: 'Employment Contract — Kamau Holdings Ltd',
    type: 'Contract',
    category: 'Business',
    status: 'signed',
    source: 'ai-generated',
    caseId: 'KE-2026-1102',
    caseName: 'Unfair Dismissal — Kamau Holdings',
    createdBy: 'Veritex AI',
    createdAt: '2026-04-15',
    updatedAt: '2 days ago',
    size: '148 KB',
    pages: 12,
    score: 91,
    riskLevel: 'low',
    expiresAt: '2027-04-15',
    signatories: [
      { name: 'James Odhiambo', role: 'Employee', status: 'signed', time: 'Apr 16, 09:21' },
      { name: 'Sarah Kamau', role: 'Employer', status: 'signed', time: 'Apr 17, 14:05' },
    ],
    versions: [
      { v: 'v3', label: 'Signed by both parties', by: 'System', time: 'Apr 17' },
      { v: 'v2', label: 'Reviewed by Advocate Njoroge', by: 'Adv. Njoroge', time: 'Apr 16' },
      { v: 'v1', label: 'AI Generated draft', by: 'Veritex AI', time: 'Apr 15' },
    ],
    activity: [
      { action: 'Signed by Sarah Kamau', time: 'Apr 17, 2:05 PM', icon: 'sign' },
      { action: 'Signed by James Odhiambo', time: 'Apr 16, 9:21 AM', icon: 'sign' },
      { action: 'Reviewed by Adv. Njoroge', time: 'Apr 16, 8:00 AM', icon: 'review' },
      { action: 'Sent to lawyer for review', time: 'Apr 15, 5:30 PM', icon: 'send' },
      { action: 'Generated by AI', time: 'Apr 15, 3:00 PM', icon: 'ai' },
    ],
    preview: `EMPLOYMENT CONTRACT

This Agreement is entered into as of 15th April 2026 between:

EMPLOYER: Kamau Holdings Ltd, a company incorporated under the Laws of Kenya (Registration No. CPR/2019/042156), hereinafter referred to as "the Employer";

AND

EMPLOYEE: James Odhiambo, National ID No. 28459102, hereinafter referred to as "the Employee".

1. POSITION & DUTIES
The Employer agrees to employ the Employee as Senior Software Engineer. The Employee shall perform duties as assigned by management, including system design, code review, and technical leadership.

2. COMMENCEMENT & DURATION
This contract commences on 1st May 2026 and shall continue unless terminated in accordance with the provisions herein.

3. REMUNERATION
The Employee shall receive a gross monthly salary of KES 180,000, subject to statutory deductions as required by Kenyan law including PAYE, NHIF, and NSSF.

4. WORKING HOURS
Normal working hours shall be 8:00 AM to 5:00 PM, Monday to Friday. Overtime shall be compensated at 1.5x the normal hourly rate.

5. LEAVE ENTITLEMENT
The Employee is entitled to 21 days of annual leave per year, accumulating at 1.75 days per month of service.`,
    aiSummary: {
      summary: "A standard Kenyan employment contract between Kamau Holdings Ltd and James Odhiambo for a Senior Software Engineer role at KES 180,000/month. Effective May 2026. Compliant with the Employment Act 2007.",
      clauses: ['Fixed-term employment with renewal option', 'Standard PAYE/NHIF/NSSF deductions', '21 days annual leave (above statutory minimum)', 'IP ownership clause favors employer', '3-month probation period'],
      flags: ['Clause 8 — Non-compete radius of 50km may be unenforceable under Section 45 of the Employment Act', 'No dispute resolution mechanism specified'],
      suggestions: ['Add mediation clause per Employment Act guidelines', 'Specify notice period for both parties (recommended 1 month minimum)'],
    },
  },
  {
    id: 'DOC-002',
    title: 'Land Sale Agreement — Plot No. LR 4902/109',
    type: 'Agreement',
    category: 'Personal',
    status: 'pending',
    source: 'lawyer-uploaded',
    caseId: 'KE-2026-0889',
    caseName: 'Land Dispute — Kiambu County',
    createdBy: 'Adv. Wanjiru Muthoni',
    createdAt: '2026-04-10',
    updatedAt: '5 days ago',
    size: '224 KB',
    pages: 18,
    score: 74,
    riskLevel: 'medium',
    expiresAt: null,
    signatories: [
      { name: 'Peter Njuguna', role: 'Seller', status: 'signed', time: 'Apr 11, 10:00' },
      { name: 'You', role: 'Buyer', status: 'pending', time: null },
    ],
    versions: [
      { v: 'v2', label: 'Revised by Advocate', by: 'Adv. Wanjiru', time: 'Apr 10' },
      { v: 'v1', label: 'Initial draft received', by: 'Adv. Wanjiru', time: 'Apr 08' },
    ],
    activity: [
      { action: 'Your signature requested', time: 'Apr 11, 10:45 AM', icon: 'alert' },
      { action: 'Signed by Peter Njuguna', time: 'Apr 11, 10:00 AM', icon: 'sign' },
      { action: 'Document revised — v2', time: 'Apr 10, 2:00 PM', icon: 'edit' },
      { action: 'Uploaded by Adv. Wanjiru', time: 'Apr 08, 9:00 AM', icon: 'upload' },
    ],
    preview: `LAND SALE AGREEMENT

This Agreement is made on the 10th day of April 2026 between:

SELLER: Peter Kamau Njuguna, holder of National ID No. 12847392, of P.O. Box 4501, Kiambu.

AND

BUYER: [Your Name], holder of National ID No. [Your ID], of [Your Address].

PROPERTY DESCRIPTION:
All that piece of land known as LR No. 4902/109, situated in Kiambu County, measuring 0.5 acres more or less, registered under the Land Registration Act, Cap 300.

PURCHASE PRICE: KES 4,500,000 (Four Million Five Hundred Thousand Kenya Shillings Only)

PAYMENT SCHEDULE:
- Deposit: KES 500,000 upon signing
- Balance: KES 4,000,000 within 60 days of signing`,
    aiSummary: {
      summary: "A land sale agreement for Plot LR 4902/109 in Kiambu County at KES 4.5M. Seller has signed. Your signature is pending. Medium risk — review flagged clauses before signing.",
      clauses: ['Purchase price KES 4.5M (market-aligned)', '60-day completion timeline', 'Deposit KES 500,000 on signing', 'Vacant possession on completion'],
      flags: ['No title search certificate attached — verify title is clean', 'Clause 7 allows seller to rescind with only 10% penalty (inadequate)', 'No caveat registration provision to protect buyer during completion'],
      suggestions: ['Demand copy of Land Search (Ministry of Lands) before signing', 'Negotiate higher rescission penalty (recommend 30%)', 'Add caveat registration clause immediately upon deposit'],
    },
  },
  {
    id: 'DOC-003',
    title: 'Statutory Declaration — GBV Incident Report',
    type: 'Court Document',
    category: 'Legal Cases',
    status: 'filed',
    source: 'user-uploaded',
    caseId: 'KE-2026-2241',
    caseName: 'GBV Protection Order',
    createdBy: 'You',
    createdAt: '2026-04-01',
    updatedAt: '2 weeks ago',
    size: '86 KB',
    pages: 4,
    score: 88,
    riskLevel: 'low',
    expiresAt: null,
    signatories: [
      { name: 'You', role: 'Declarant', status: 'signed', time: 'Apr 1, 11:30' },
      { name: 'Commissioner for Oaths', role: 'Witness', status: 'signed', time: 'Apr 1, 11:45' },
    ],
    versions: [
      { v: 'v1', label: 'Filed in court', by: 'You', time: 'Apr 01' },
    ],
    activity: [
      { action: 'Filed at Milimani Law Courts', time: 'Apr 01, 12:00 PM', icon: 'sign' },
      { action: 'Commissioned by Oaths Commissioner', time: 'Apr 01, 11:45 AM', icon: 'review' },
      { action: 'Uploaded and submitted', time: 'Apr 01, 11:30 AM', icon: 'upload' },
    ],
    preview: `STATUTORY DECLARATION

I, [Name Redacted], of P.O. Box [Redacted], Nairobi, do hereby solemnly and sincerely declare:

1. That I am the Applicant in this matter and I make this declaration in support of my application for a Protection Order under the Protection Against Domestic Violence Act No. 2 of 2015.

2. That on the [Date Redacted], at approximately [Time Redacted], the Respondent did unlawfully assault me at [Location Redacted], causing me bodily harm as evidenced by the medical examination report annexed hereto as Exhibit A.

3. That the Respondent has repeatedly engaged in conduct constituting domestic violence as defined under Section 3 of the Protection Against Domestic Violence Act...`,
    aiSummary: {
      summary: "A sworn statutory declaration supporting a Protection Order application under the Domestic Violence Act 2015. Filed and commissioned. Strong legal standing — well-structured and properly sworn.",
      clauses: ['Filed under Protection Against Domestic Violence Act 2015', 'Sworn before Commissioner for Oaths', 'Medical report annexed as Exhibit A'],
      flags: [],
      suggestions: ['Attach police abstract OB number if available', 'Request hearing date from court registry'],
    },
  },
  {
    id: 'DOC-004',
    title: 'Demand Letter — Debt Recovery KES 340,000',
    type: 'Court Document',
    category: 'Business',
    status: 'draft',
    source: 'ai-generated',
    caseId: null,
    caseName: null,
    createdBy: 'Veritex AI',
    createdAt: '2026-04-28',
    updatedAt: 'Today',
    size: '42 KB',
    pages: 2,
    score: 62,
    riskLevel: 'low',
    expiresAt: null,
    signatories: [],
    versions: [
      { v: 'v1', label: 'AI Generated draft', by: 'Veritex AI', time: 'Apr 28' },
    ],
    activity: [
      { action: 'Draft created by AI', time: 'Apr 28, 9:00 AM', icon: 'ai' },
    ],
    preview: `WITHOUT PREJUDICE

28th April 2026

The Director
[Debtor Company Name]
P.O. Box [Address]
Nairobi

Dear Sir/Madam,

RE: OUTSTANDING DEBT — KES 340,000

We write on behalf of our client, [Your Name/Company], to formally demand payment of the outstanding sum of Kenya Shillings Three Hundred and Forty Thousand (KES 340,000) arising from [nature of debt — please specify].

DEMAND: You are hereby required to settle the above outstanding amount in FULL within FOURTEEN (14) DAYS from the date of this letter.

CONSEQUENCES OF NON-PAYMENT: Failure to comply with this demand will result in our client instituting legal proceedings against you without further notice, in which event you shall be liable for...`,
    aiSummary: {
      summary: "A demand letter for debt recovery of KES 340,000. Currently a draft — requires your specific details before sending. Score is 62 due to missing placeholders.",
      clauses: ['14-day compliance window', 'Without prejudice heading', 'Litigation threat on non-compliance'],
      flags: ['3 placeholder fields remain unfilled (debtor details, nature of debt)', 'No interest clause — add statutory interest at 14% per annum'],
      suggestions: ['Fill all [bracket] placeholders before sending', 'Add bank account details for payment', 'Consider sending via registered post + email for proof of service'],
    },
  },
  {
    id: 'DOC-005',
    title: 'Tenancy Agreement — House No. 14B, Westlands',
    type: 'Agreement',
    category: 'Personal',
    status: 'approved',
    source: 'ai-generated',
    caseId: null,
    caseName: null,
    createdBy: 'Veritex AI',
    createdAt: '2026-03-01',
    updatedAt: '2 months ago',
    size: '176 KB',
    pages: 10,
    score: 95,
    riskLevel: 'low',
    expiresAt: '2027-03-01',
    signatories: [
      { name: 'You', role: 'Tenant', status: 'signed', time: 'Mar 2, 10:00' },
      { name: 'John Mwangi', role: 'Landlord', status: 'signed', time: 'Mar 2, 15:30' },
    ],
    versions: [
      { v: 'v2', label: 'Final signed version', by: 'System', time: 'Mar 02' },
      { v: 'v1', label: 'AI Generated draft', by: 'Veritex AI', time: 'Mar 01' },
    ],
    activity: [
      { action: 'Signed by Landlord John Mwangi', time: 'Mar 2, 3:30 PM', icon: 'sign' },
      { action: 'Signed by Tenant (You)', time: 'Mar 2, 10:00 AM', icon: 'sign' },
      { action: 'Generated by AI', time: 'Mar 1, 2:00 PM', icon: 'ai' },
    ],
    preview: `RESIDENTIAL TENANCY AGREEMENT

This Agreement is entered into on the 1st day of March 2026 between:

LANDLORD: John Kamau Mwangi, National ID No. 34821094

TENANT: [Your Name], National ID No. [Your ID]

PROPERTY: House No. 14B, Westlands, Nairobi, comprising 3 bedrooms, 2 bathrooms, and a sitting room.

TERM: 12 months commencing 1st March 2026 to 28th February 2027, with option to renew.

RENT: KES 55,000 per month, payable on or before the 5th day of each month.

DEPOSIT: KES 110,000 (2 months' rent) refundable upon vacating in good condition.`,
    aiSummary: {
      summary: "A fully executed residential tenancy agreement for 14B Westlands at KES 55,000/month. Expires March 2027. Excellent score of 95 — fully compliant with the Landlord & Tenant Act.",
      clauses: ['12-month fixed term (Mar 2026 – Feb 2027)', 'KES 55,000/month rent', '2-month refundable deposit (KES 110,000)', 'Renewal option with 30-day notice'],
      flags: [],
      suggestions: ['Set a reminder 60 days before expiry (Jan 2027) for renewal negotiation'],
    },
  },
  {
    id: 'DOC-006',
    title: 'Affidavit of Service — Court Summons',
    type: 'Evidence',
    category: 'Legal Cases',
    status: 'needs-attention',
    source: 'lawyer-uploaded',
    caseId: 'KE-2026-0334',
    caseName: 'Commercial Dispute — Invoice Recovery',
    createdBy: 'Adv. Kariuki Maina',
    createdAt: '2026-04-20',
    updatedAt: '1 week ago',
    size: '58 KB',
    pages: 3,
    score: 55,
    riskLevel: 'high',
    expiresAt: null,
    signatories: [
      { name: 'Court Process Server', role: 'Server', status: 'signed', time: 'Apr 20, 14:00' },
    ],
    activity: [
      { action: 'AI flagged missing stamp', time: 'Apr 21, 8:00 AM', icon: 'alert' },
      { action: 'Uploaded by Adv. Kariuki', time: 'Apr 20, 2:00 PM', icon: 'upload' },
    ],
    preview: `AFFIDAVIT OF SERVICE

I, [Process Server Name], Process Server, of P.O. Box [Address], Nairobi, do hereby make oath and state:

1. That I am a process server duly authorized to serve court documents in the Republic of Kenya.

2. That on the 20th day of April 2026 at approximately 2:00 PM, I personally served the above-named defendant with the Plaint and Summons to Appear in the above-captioned matter at [Address Served].

3. That the defendant appeared to be approximately [Age] years old, and identified himself/herself as [Name]...`,
    aiSummary: {
      summary: "An affidavit of service for court summons in case KE-2026-0334. Requires immediate attention — missing official court stamp and process server's registration number.",
      clauses: ['Personal service confirmed', 'Date and time of service recorded'],
      flags: ['⚠️ Missing official court stamp — document may be rejected', "Process server's registration number absent — required by Civil Procedure Rules", 'Name of person served is blank — must be completed'],
      suggestions: ['Return to lawyer immediately for correction', 'Ensure stamped within 7 days to avoid service defect challenge', 'Confirm process server is registered under Civil Procedure Act'],
    },
  },
];

const CATEGORIES = [
  { id: 'all', label: 'All Documents', icon: Layers, count: 6 },
  { id: 'Personal', label: 'Personal', icon: User, count: 2 },
  { id: 'Business', label: 'Business', icon: Briefcase, count: 2 },
  { id: 'Legal Cases', label: 'Legal Cases', icon: Scale, count: 2 },
  { id: 'Evidence', label: 'Evidence', icon: FileCheck, count: 1 },
];

const DOC_TYPES = ['All', 'Contract', 'Agreement', 'Court Document', 'Evidence'];
const SOURCES = ['All', 'ai-generated', 'user-uploaded', 'lawyer-uploaded'];
const STATUSES = ['all', 'draft', 'pending', 'approved', 'signed', 'filed', 'needs-attention'];

const AI_SUGGESTIONS = [
  'Explain this contract in simple terms',
  'Highlight any legal risks',
  'What clauses should I add?',
  'Is this legally binding in Kenya?',
  'Compare this to standard Kenyan law',
];

/* ─────────────────────────────────────────────
   UTILITY / HELPERS
───────────────────────────────────────────── */
function statusConfig(status) {
  return {
    draft: { label: 'Draft', color: 'text-white/50', bg: 'bg-white/6', border: 'border-white/10', dot: 'bg-white/30' },
    pending: { label: 'Pending Signature', color: 'text-amber-400', bg: 'bg-amber-500/10', border: 'border-amber-500/25', dot: 'bg-amber-400' },
    approved: { label: 'Approved', color: 'text-blue-400', bg: 'bg-blue-500/10', border: 'border-blue-500/25', dot: 'bg-blue-400' },
    signed: { label: 'Signed', color: 'text-green-400', bg: 'bg-green-500/10', border: 'border-green-500/25', dot: 'bg-green-400' },
    filed: { label: 'Filed in Court', color: 'text-purple-400', bg: 'bg-purple-500/10', border: 'border-purple-500/25', dot: 'bg-purple-400' },
    'needs-attention': { label: 'Needs Attention', color: 'text-red-400', bg: 'bg-red-500/10', border: 'border-red-500/25', dot: 'bg-red-400 animate-pulse' },
  }[status] || { label: status, color: 'text-white/40', bg: 'bg-white/5', border: 'border-white/10', dot: 'bg-white/30' };
}

function sourceConfig(source) {
  return {
    'ai-generated': { label: 'AI Generated', icon: Brain, color: 'text-[#D4AF37]' },
    'user-uploaded': { label: 'User Upload', icon: UploadCloud, color: 'text-blue-400' },
    'lawyer-uploaded': { label: 'Lawyer Upload', icon: Scale, color: 'text-purple-400' },
  }[source] || { label: source, icon: FileText, color: 'text-white/40' };
}

function riskConfig(risk) {
  return {
    low: { label: 'Low Risk', color: 'text-green-400', bar: 'bg-green-400' },
    medium: { label: 'Med Risk', color: 'text-amber-400', bar: 'bg-amber-400' },
    high: { label: 'High Risk', color: 'text-red-400', bar: 'bg-red-400' },
  }[risk] || { label: 'Unknown', color: 'text-white/30', bar: 'bg-white/20' };
}

function typeIcon(type) {
  return { Contract: '📋', Agreement: '🤝', 'Court Document': '⚖️', Evidence: '🔍', 'Personal Document': '👤' }[type] || '📄';
}

function activityIcon(icon) {
  const map = { sign: CheckCircle, review: Eye, send: Send, ai: Brain, upload: UploadCloud, edit: Edit3, alert: AlertCircle };
  const Icon = map[icon] || Activity;
  const colors = { sign: 'text-green-400', review: 'text-blue-400', send: 'text-purple-400', ai: 'text-[#D4AF37]', upload: 'text-cyan-400', edit: 'text-orange-400', alert: 'text-red-400' };
  return { Icon, color: colors[icon] || 'text-white/40' };
}

/* ─────────────────────────────────────────────
   SMALL UI PRIMITIVES
───────────────────────────────────────────── */
function Card({ children, className = '', onClick }) {
  return (
    <div
      onClick={onClick}
      className={`rounded-2xl border border-white/6 bg-white/[0.03] backdrop-blur-sm ${className}`}
    >
      {children}
    </div>
  );
}

function StatusBadge({ status, size = 'sm' }) {
  const cfg = statusConfig(status);
  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-bold border ${cfg.color} ${cfg.bg} ${cfg.border}`}>
      <span className={`w-1.5 h-1.5 rounded-full ${cfg.dot}`} />
      {cfg.label}
    </span>
  );
}

function ScoreMeter({ score }) {
  const color = score >= 80 ? '#4ade80' : score >= 60 ? GOLD : '#f87171';
  return (
    <div className="flex items-center gap-2">
      <div className="relative w-8 h-8">
        <svg viewBox="0 0 32 32" className="w-full h-full -rotate-90">
          <circle cx="16" cy="16" r="12" fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="3" />
          <motion.circle
            cx="16" cy="16" r="12"
            fill="none" stroke={color} strokeWidth="3"
            strokeLinecap="round"
            strokeDasharray={`${2 * Math.PI * 12}`}
            initial={{ strokeDashoffset: 2 * Math.PI * 12 }}
            animate={{ strokeDashoffset: 2 * Math.PI * 12 * (1 - score / 100) }}
            transition={{ duration: 1, delay: 0.3, ease: 'easeOut' }}
          />
        </svg>
        <span className="absolute inset-0 flex items-center justify-center text-[8px] font-black" style={{ color }}>{score}</span>
      </div>
    </div>
  );
}

/* ─────────────────────────────────────────────
   AI BAR
───────────────────────────────────────────── */
function AIBar({ onQuery, doc }) {
  const [query, setQuery] = useState('');
  const [focused, setFocused] = useState(false);
  const [thinking, setThinking] = useState(false);
  const [response, setResponse] = useState(null);

  const submit = (q) => {
    const text = q || query;
    if (!text.trim()) return;
    setQuery(text);
    setFocused(false);
    setThinking(true);
    setResponse(null);
    setTimeout(() => {
      setThinking(false);
      setResponse(
        doc
          ? `Based on "${doc.title}": ${doc.aiSummary.summary} Key flags: ${doc.aiSummary.flags[0] || 'None detected.'}`
          : "I can analyse any document in your vault. Select a document first, then ask me anything about it — risks, clauses, what to change, or whether it's legally binding in Kenya."
      );
    }, 2200);
  };

  return (
    <div className="rounded-2xl border border-[#D4AF37]/20 bg-[#D4AF37]/4 overflow-hidden">
      <div className="flex items-center gap-3 px-4 py-3">
        <div className="flex items-center gap-2 flex-shrink-0">
          <div className="w-6 h-6 rounded-lg bg-[#D4AF37]/20 border border-[#D4AF37]/30 flex items-center justify-center">
            <Sparkles className="w-3.5 h-3.5 text-[#D4AF37]" />
          </div>
          <span className="text-[#D4AF37] text-xs font-bold hidden sm:block">Veritas AI</span>
        </div>
        <div className="flex-1 relative">
          <input
            value={query}
            onChange={e => setQuery(e.target.value)}
            onFocus={() => setFocused(true)}
            onBlur={() => setTimeout(() => setFocused(false), 150)}
            onKeyDown={e => e.key === 'Enter' && submit()}
            placeholder={doc ? `Ask about "${doc.title.substring(0, 30)}..."` : 'Ask Veritas AI about your documents…'}
            className="w-full bg-transparent text-white/80 text-sm outline-none placeholder:text-white/25"
          />
          {focused && (
            <motion.div
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              className="absolute top-full left-0 right-0 mt-2 rounded-xl border border-white/8 bg-[#1a1d2e] z-30 overflow-hidden shadow-2xl"
            >
              <p className="text-[10px] text-white/25 uppercase tracking-widest px-3 pt-3 pb-1 font-bold">Suggestions</p>
              {AI_SUGGESTIONS.map((s, i) => (
                <button key={i} onMouseDown={() => submit(s)}
                  className="w-full text-left px-3 py-2.5 text-xs text-white/60 hover:bg-white/5 hover:text-white flex items-center gap-2 transition-colors">
                  <Sparkles className="w-3 h-3 text-[#D4AF37]/50" /> {s}
                </button>
              ))}
            </motion.div>
          )}
        </div>
        <button onClick={() => submit()} className="flex-shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#D4AF37] hover:bg-[#c9a430] text-[#12141f] text-xs font-black transition-all">
          <Send className="w-3 h-3" /> Ask
        </button>
      </div>

      <AnimatePresence>
        {thinking && (
          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
            className="border-t border-[#D4AF37]/10 px-4 py-3 flex items-center gap-2">
            <Loader className="w-3.5 h-3.5 text-[#D4AF37] animate-spin" />
            <span className="text-[#D4AF37]/70 text-xs">Analysing Kenya Law corpus…</span>
          </motion.div>
        )}
        {response && !thinking && (
          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
            className="border-t border-[#D4AF37]/10 px-4 py-3 flex items-start gap-2">
            <CheckCircle className="w-3.5 h-3.5 text-[#D4AF37] mt-0.5 flex-shrink-0" />
            <p className="text-white/70 text-xs leading-relaxed">{response}</p>
            <button onClick={() => setResponse(null)} className="ml-auto flex-shrink-0 text-white/20 hover:text-white/50">
              <X className="w-3.5 h-3.5" />
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

/* ─────────────────────────────────────────────
   DOCUMENT CARD (GRID)
───────────────────────────────────────────── */
function DocCard({ doc, selected, onClick }) {
  const src = sourceConfig(doc.source);
  const risk = riskConfig(doc.riskLevel);
  const SrcIcon = src.icon;

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
      whileHover={{ y: -3 }}
      onClick={onClick}
      className={`relative rounded-2xl border cursor-pointer transition-all duration-200 group overflow-hidden ${
        selected
          ? 'border-[#D4AF37]/50 bg-[#D4AF37]/6 shadow-xl shadow-[#D4AF37]/8'
          : 'border-white/6 bg-white/[0.03] hover:border-white/12 hover:bg-white/[0.05]'
      }`}
    >
      {/* Needs attention accent */}
      {doc.status === 'needs-attention' && (
        <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-red-500 to-orange-500" />
      )}
      {selected && <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-[#D4AF37] to-[#f0cc55]" />}

      <div className="p-5">
        {/* Header row */}
        <div className="flex items-start justify-between mb-3">
          <div className="text-2xl">{typeIcon(doc.type)}</div>
          <div className="flex items-center gap-2">
            <ScoreMeter score={doc.score} />
            <StatusBadge status={doc.status} />
          </div>
        </div>

        {/* Title */}
        <h3 className="text-white font-bold text-sm leading-snug mb-1 line-clamp-2">{doc.title}</h3>
        <p className="text-white/30 text-[11px] mb-3">{doc.type}</p>

        {/* Source + case */}
        <div className="space-y-1.5 mb-4">
          <div className="flex items-center gap-1.5">
            <SrcIcon className={`w-3 h-3 ${src.color}`} />
            <span className={`text-[10px] font-semibold ${src.color}`}>{src.label}</span>
          </div>
          {doc.caseName && (
            <div className="flex items-center gap-1.5">
              <Link2 className="w-3 h-3 text-white/20" />
              <span className="text-[10px] text-white/25 truncate">{doc.caseId}</span>
            </div>
          )}
        </div>

        {/* Bottom row */}
        <div className="flex items-center justify-between pt-3 border-t border-white/5">
          <div className="flex items-center gap-1">
            <Clock className="w-3 h-3 text-white/20" />
            <span className="text-[10px] text-white/30">{doc.updatedAt}</span>
          </div>
          <div className="flex items-center gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity">
            <button className="w-6 h-6 rounded-lg bg-white/6 hover:bg-white/12 flex items-center justify-center" onClick={e => { e.stopPropagation(); }}>
              <Eye className="w-3 h-3 text-white/40" />
            </button>
            <button className="w-6 h-6 rounded-lg bg-white/6 hover:bg-white/12 flex items-center justify-center" onClick={e => { e.stopPropagation(); }}>
              <Download className="w-3 h-3 text-white/40" />
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────
   DOCUMENT ROW (TABLE)
───────────────────────────────────────────── */
function DocRow({ doc, selected, onClick }) {
  const src = sourceConfig(doc.source);
  const SrcIcon = src.icon;

  return (
    <motion.div
      layout
      initial={{ opacity: 0, x: -10 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0 }}
      onClick={onClick}
      className={`flex items-center gap-4 px-5 py-3.5 cursor-pointer transition-all rounded-xl group ${
        selected ? 'bg-[#D4AF37]/6 border border-[#D4AF37]/25' : 'border border-transparent hover:bg-white/[0.03] hover:border-white/6'
      }`}
    >
      <div className="text-xl w-8 flex-shrink-0">{typeIcon(doc.type)}</div>
      <div className="flex-1 min-w-0">
        <p className="text-white text-sm font-semibold truncate">{doc.title}</p>
        <div className="flex items-center gap-2 mt-0.5">
          <span className="text-white/25 text-[10px]">{doc.type}</span>
          {doc.caseId && <><span className="text-white/15">·</span><span className="text-white/25 text-[10px] font-mono">{doc.caseId}</span></>}
        </div>
      </div>
      <div className="flex items-center gap-1.5 flex-shrink-0">
        <SrcIcon className={`w-3 h-3 ${src.color}`} />
        <span className={`text-[10px] font-semibold ${src.color} hidden sm:block`}>{src.label}</span>
      </div>
      <div className="flex-shrink-0"><StatusBadge status={doc.status} /></div>
      <div className="flex-shrink-0 hidden lg:flex items-center gap-1">
        <ScoreMeter score={doc.score} />
      </div>
      <div className="flex-shrink-0 hidden md:block">
        <span className="text-white/25 text-[11px]">{doc.updatedAt}</span>
      </div>
      <div className="flex items-center gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0">
        <button className="w-7 h-7 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center" onClick={e => e.stopPropagation()}>
          <Eye className="w-3.5 h-3.5 text-white/40" />
        </button>
        <button className="w-7 h-7 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center" onClick={e => e.stopPropagation()}>
          <Download className="w-3.5 h-3.5 text-white/40" />
        </button>
        <button className="w-7 h-7 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center" onClick={e => e.stopPropagation()}>
          <MoreHorizontal className="w-3.5 h-3.5 text-white/30" />
        </button>
      </div>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────
   DETAIL PANEL — TABS
───────────────────────────────────────────── */

// Tab: Overview
function TabOverview({ doc }) {
  return (
    <div className="space-y-5">
      {/* Preview */}
      <div>
        <p className="text-[10px] text-white/25 uppercase tracking-widest font-bold mb-2">Document Preview</p>
        <div className="rounded-xl border border-white/6 bg-[#0e1019] p-5 max-h-56 overflow-y-auto">
          <pre className="text-white/60 text-[11px] leading-relaxed font-mono whitespace-pre-wrap">{doc.preview}</pre>
          <div className="mt-3 pt-3 border-t border-white/5 flex items-center gap-2">
            <div className="w-1.5 h-1.5 rounded-full bg-white/20" />
            <span className="text-white/20 text-[10px]">Document continues — {doc.pages} pages total</span>
          </div>
        </div>
      </div>

      {/* Meta */}
      <div className="grid grid-cols-2 gap-2">
        {[
          { label: 'Created By', value: doc.createdBy },
          { label: 'Created', value: doc.createdAt },
          { label: 'Pages', value: `${doc.pages} pages` },
          { label: 'File Size', value: doc.size },
          { label: 'Category', value: doc.category },
          { label: 'Expires', value: doc.expiresAt || 'No expiry' },
        ].map(({ label, value }, i) => (
          <div key={i} className="p-3 rounded-xl bg-white/3 border border-white/5">
            <p className="text-white/25 text-[10px] uppercase tracking-widest mb-0.5">{label}</p>
            <p className="text-white/80 text-xs font-semibold">{value}</p>
          </div>
        ))}
      </div>

      {/* Lifecycle */}
      <div>
        <p className="text-[10px] text-white/25 uppercase tracking-widest font-bold mb-3">Document Lifecycle</p>
        <div className="flex items-center gap-1 overflow-x-auto pb-1">
          {['Generated', 'Edited', 'Reviewed', 'Approved', 'Signed', 'Stored'].map((step, i) => {
            const completed = { draft: 1, pending: 3, approved: 4, signed: 5, filed: 6, 'needs-attention': 3 }[doc.status] > i;
            const active = { draft: 0, pending: 2, approved: 3, signed: 4, filed: 5, 'needs-attention': 2 }[doc.status] === i;
            return (
              <React.Fragment key={i}>
                <div className={`flex-shrink-0 text-center`}>
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[9px] font-black mb-1 border ${
                    completed ? 'bg-green-500/20 border-green-500/40 text-green-400' :
                    active ? 'bg-[#D4AF37]/20 border-[#D4AF37]/40 text-[#D4AF37]' :
                    'bg-white/4 border-white/8 text-white/20'
                  }`}>{completed ? '✓' : i + 1}</div>
                  <p className={`text-[9px] font-semibold ${completed ? 'text-green-400' : active ? 'text-[#D4AF37]' : 'text-white/20'}`}>{step}</p>
                </div>
                {i < 5 && <div className={`flex-1 h-px ${completed ? 'bg-green-500/30' : 'bg-white/6'}`} />}
              </React.Fragment>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// Tab: AI Analysis
function TabAI({ doc }) {
  const risk = riskConfig(doc.riskLevel);
  return (
    <div className="space-y-4">
      {/* Score + Risk */}
      <div className="flex gap-3">
        <div className="flex-1 p-4 rounded-xl bg-white/3 border border-white/6 text-center">
          <p className="text-[10px] text-white/25 uppercase tracking-widest mb-2">Document Score</p>
          <p className="text-4xl font-black" style={{ color: doc.score >= 80 ? '#4ade80' : doc.score >= 60 ? GOLD : '#f87171' }}>{doc.score}</p>
          <p className="text-white/30 text-[10px] mt-1">out of 100</p>
        </div>
        <div className="flex-1 p-4 rounded-xl bg-white/3 border border-white/6 text-center">
          <p className="text-[10px] text-white/25 uppercase tracking-widest mb-2">Risk Level</p>
          <p className={`text-2xl font-black ${risk.color} capitalize mt-1`}>{doc.riskLevel}</p>
          <div className="mt-2 h-1.5 rounded-full bg-white/6 overflow-hidden">
            <div className={`h-full rounded-full ${risk.bar}`} style={{ width: doc.riskLevel === 'low' ? '25%' : doc.riskLevel === 'medium' ? '60%' : '90%' }} />
          </div>
        </div>
      </div>

      {/* Summary */}
      <div className="p-4 rounded-xl border border-[#D4AF37]/15 bg-[#D4AF37]/4">
        <div className="flex items-center gap-2 mb-2">
          <Sparkles className="w-3.5 h-3.5 text-[#D4AF37]" />
          <span className="text-[#D4AF37] text-[10px] font-bold uppercase tracking-widest">AI Summary</span>
        </div>
        <p className="text-white/70 text-xs leading-relaxed">{doc.aiSummary.summary}</p>
      </div>

      {/* Key Clauses */}
      <div>
        <p className="text-[10px] text-white/25 uppercase tracking-widest font-bold mb-2">Key Clauses</p>
        <div className="space-y-1.5">
          {doc.aiSummary.clauses.map((c, i) => (
            <div key={i} className="flex items-start gap-2 p-2.5 rounded-lg bg-white/3 border border-white/5">
              <CheckCircle className="w-3 h-3 text-blue-400 mt-0.5 flex-shrink-0" />
              <span className="text-white/65 text-xs">{c}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Red Flags */}
      {doc.aiSummary.flags.length > 0 && (
        <div>
          <p className="text-[10px] text-red-400/70 uppercase tracking-widest font-bold mb-2 flex items-center gap-1.5">
            <AlertTriangle className="w-3 h-3" /> Red Flags
          </p>
          <div className="space-y-1.5">
            {doc.aiSummary.flags.map((f, i) => (
              <div key={i} className="flex items-start gap-2 p-2.5 rounded-lg bg-red-500/6 border border-red-500/15">
                <AlertCircle className="w-3 h-3 text-red-400 mt-0.5 flex-shrink-0" />
                <span className="text-red-300/80 text-xs">{f}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Suggestions */}
      {doc.aiSummary.suggestions.length > 0 && (
        <div>
          <p className="text-[10px] text-[#D4AF37]/70 uppercase tracking-widest font-bold mb-2">Suggestions</p>
          <div className="space-y-1.5">
            {doc.aiSummary.suggestions.map((s, i) => (
              <div key={i} className="flex items-start gap-2 p-2.5 rounded-lg bg-[#D4AF37]/5 border border-[#D4AF37]/12">
                <TrendingUp className="w-3 h-3 text-[#D4AF37] mt-0.5 flex-shrink-0" />
                <span className="text-[#D4AF37]/80 text-xs">{s}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// Tab: Signatures
function TabSignatures({ doc }) {
  const [inviting, setInviting] = useState(false);
  const [email, setEmail] = useState('');

  const allSigned = doc.signatories.every(s => s.status === 'signed');

  return (
    <div className="space-y-5">
      {/* Status banner */}
      <div className={`p-4 rounded-xl border flex items-center gap-3 ${
        allSigned ? 'border-green-500/20 bg-green-500/5' :
        doc.signatories.length === 0 ? 'border-white/8 bg-white/3' :
        'border-amber-500/20 bg-amber-500/5'
      }`}>
        {allSigned ? <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0" /> :
         doc.signatories.length === 0 ? <PenTool className="w-5 h-5 text-white/30 flex-shrink-0" /> :
         <Clock className="w-5 h-5 text-amber-400 flex-shrink-0" />}
        <div>
          <p className={`text-sm font-bold ${allSigned ? 'text-green-400' : doc.signatories.length === 0 ? 'text-white/40' : 'text-amber-400'}`}>
            {allSigned ? 'Fully Executed' : doc.signatories.length === 0 ? 'No signatures required' : `Awaiting ${doc.signatories.filter(s => s.status !== 'signed').length} signature(s)`}
          </p>
          <p className="text-white/30 text-xs">
            {doc.signatories.filter(s => s.status === 'signed').length}/{doc.signatories.length} signed
          </p>
        </div>
      </div>

      {/* Signatories */}
      {doc.signatories.length > 0 && (
        <div className="space-y-2">
          <p className="text-[10px] text-white/25 uppercase tracking-widest font-bold">Signatories</p>
          {doc.signatories.map((sig, i) => (
            <div key={i} className="flex items-center gap-3 p-3.5 rounded-xl border border-white/6 bg-white/3">
              <div className={`w-8 h-8 rounded-full border flex items-center justify-center text-sm font-black ${
                sig.status === 'signed' ? 'bg-green-500/15 border-green-500/30 text-green-400' : 'bg-white/6 border-white/10 text-white/30'
              }`}>{sig.name[0]}</div>
              <div className="flex-1">
                <p className="text-white/80 text-sm font-semibold">{sig.name}</p>
                <p className="text-white/30 text-[11px]">{sig.role}</p>
              </div>
              {sig.status === 'signed' ? (
                <div className="text-right">
                  <div className="flex items-center gap-1 justify-end">
                    <CheckCircle className="w-3.5 h-3.5 text-green-400" />
                    <span className="text-green-400 text-[10px] font-bold">Signed</span>
                  </div>
                  <p className="text-white/20 text-[9px] mt-0.5">{sig.time}</p>
                </div>
              ) : (
                <div className="flex items-center gap-1.5">
                  <span className="text-amber-400/70 text-[10px] font-bold">Pending</span>
                  <button className="px-2.5 py-1 rounded-lg bg-amber-500/15 border border-amber-500/25 text-amber-400 text-[10px] font-bold hover:bg-amber-500/25 transition-colors">
                    Remind
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* E-Sign CTA or Invite */}
      {doc.status === 'draft' || doc.status === 'approved' ? (
        <button className="w-full py-3 rounded-xl bg-[#D4AF37] hover:bg-[#c9a430] text-[#12141f] text-sm font-black transition-all flex items-center justify-center gap-2">
          <PenTool className="w-4 h-4" /> Sign This Document
        </button>
      ) : null}

      {!inviting ? (
        <button onClick={() => setInviting(true)}
          className="w-full py-3 rounded-xl border border-white/8 bg-white/3 text-white/50 hover:text-white hover:border-white/15 text-sm font-semibold transition-all flex items-center justify-center gap-2">
          <Plus className="w-4 h-4" /> Invite Others to Sign
        </button>
      ) : (
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="p-4 rounded-xl border border-white/8 bg-white/3 space-y-3">
          <p className="text-white/60 text-xs font-semibold">Invite a signatory</p>
          <input value={email} onChange={e => setEmail(e.target.value)} placeholder="email@example.com"
            className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white/70 text-sm outline-none placeholder:text-white/20 focus:border-[#D4AF37]/40 transition-colors" />
          <div className="flex gap-2">
            <button onClick={() => setInviting(false)} className="flex-1 py-2 rounded-lg bg-white/5 border border-white/8 text-white/40 text-xs font-semibold">Cancel</button>
            <button className="flex-1 py-2 rounded-lg bg-[#D4AF37] text-[#12141f] text-xs font-black flex items-center justify-center gap-1">
              <Send className="w-3 h-3" /> Send Invite
            </button>
          </div>
        </motion.div>
      )}
    </div>
  );
}

// Tab: Versions
function TabVersions({ doc }) {
  return (
    <div className="space-y-4">
      <p className="text-[10px] text-white/25 uppercase tracking-widest font-bold">Version History</p>
      <div className="relative">
        <div className="absolute left-3.5 top-2 bottom-2 w-px bg-white/8" />
        <div className="space-y-2">
          {doc.versions.map((v, i) => (
            <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.08 }}
              className={`flex items-start gap-4 pl-10 relative ${i === 0 ? 'opacity-100' : 'opacity-70 hover:opacity-100 transition-opacity'}`}>
              <div className={`absolute left-2 top-3 w-3 h-3 rounded-full border-2 ${i === 0 ? 'bg-[#D4AF37] border-[#D4AF37]' : 'bg-[#1a1d2e] border-white/20'}`} />
              <div className="flex-1 p-3 rounded-xl border border-white/6 bg-white/3">
                <div className="flex items-center justify-between mb-1">
                  <span className={`text-[10px] font-black ${i === 0 ? 'text-[#D4AF37]' : 'text-white/30'}`}>{v.v} {i === 0 ? '· CURRENT' : ''}</span>
                  <span className="text-white/20 text-[10px]">{v.time}</span>
                </div>
                <p className="text-white/70 text-xs font-semibold">{v.label}</p>
                <p className="text-white/30 text-[10px] mt-0.5">by {v.by}</p>
                {i > 0 && (
                  <button className="mt-2 flex items-center gap-1 text-[10px] text-white/30 hover:text-white/60 transition-colors">
                    <RotateCcw className="w-3 h-3" /> Restore this version
                  </button>
                )}
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Access log */}
      <div>
        <p className="text-[10px] text-white/25 uppercase tracking-widest font-bold mb-3">Activity Log</p>
        <div className="space-y-2">
          {doc.activity.map((a, i) => {
            const { Icon, color } = activityIcon(a.icon);
            return (
              <div key={i} className="flex items-center gap-3 py-2 border-b border-white/4 last:border-0">
                <div className={`w-6 h-6 rounded-lg bg-white/4 flex items-center justify-center flex-shrink-0`}>
                  <Icon className={`w-3 h-3 ${color}`} />
                </div>
                <div className="flex-1">
                  <p className="text-white/65 text-xs">{a.action}</p>
                </div>
                <span className="text-white/20 text-[10px] flex-shrink-0">{a.time}</span>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// Tab: Actions
function TabActions({ doc, onClose }) {
  const [lawyerNote, setLawyerNote] = useState('');
  const [sent, setSent] = useState(false);

  const sendToLawyer = () => {
    if (!lawyerNote.trim()) return;
    setSent(true);
    setTimeout(() => setSent(false), 4000);
    setLawyerNote('');
  };

  return (
    <div className="space-y-4">
      {/* Quick actions */}
      <div>
        <p className="text-[10px] text-white/25 uppercase tracking-widest font-bold mb-3">Quick Actions</p>
        <div className="grid grid-cols-2 gap-2">
          {[
            { icon: Edit3, label: 'Edit Document', color: 'text-white/60', disabled: doc.status === 'filed' },
            { icon: Download, label: 'Download PDF', color: 'text-blue-400' },
            { icon: Share2, label: 'Share Secure Link', color: 'text-purple-400' },
            { icon: Copy, label: 'Duplicate', color: 'text-white/60' },
            { icon: ExternalLink, label: 'Open Full View', color: 'text-[#D4AF37]' },
            { icon: Archive, label: 'Archive', color: 'text-white/30' },
          ].map(({ icon: Icon, label, color, disabled }, i) => (
            <button key={i} disabled={disabled}
              className={`flex items-center gap-2 p-3 rounded-xl border border-white/6 bg-white/3 hover:border-white/12 hover:bg-white/5 transition-all text-left ${disabled ? 'opacity-30 cursor-not-allowed' : ''}`}>
              <Icon className={`w-3.5 h-3.5 ${color}`} />
              <span className="text-white/60 text-xs font-semibold">{label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Send to lawyer */}
      <div className="p-4 rounded-xl border border-purple-500/15 bg-purple-500/4">
        <div className="flex items-center gap-2 mb-3">
          <Scale className="w-3.5 h-3.5 text-purple-400" />
          <p className="text-purple-400 text-xs font-bold uppercase tracking-widest">Send to Lawyer for Review</p>
        </div>
        {sent ? (
          <div className="flex items-center gap-2 py-2">
            <CheckCircle className="w-4 h-4 text-green-400" />
            <p className="text-green-400 text-sm font-semibold">Sent to your assigned advocate!</p>
          </div>
        ) : (
          <>
            <textarea value={lawyerNote} onChange={e => setLawyerNote(e.target.value)} rows={2}
              placeholder="Add a note for your lawyer... e.g. 'Please confirm clause 4 is enforceable'"
              className="w-full px-3 py-2 rounded-xl bg-white/5 border border-white/10 text-white/70 text-xs outline-none resize-none placeholder:text-white/20 focus:border-purple-500/30 transition-colors mb-2" />
            <button onClick={sendToLawyer} disabled={!lawyerNote.trim()}
              className="w-full py-2.5 rounded-xl bg-purple-500/20 hover:bg-purple-500/30 border border-purple-500/25 text-purple-400 text-xs font-black transition-all flex items-center justify-center gap-2 disabled:opacity-40 disabled:cursor-not-allowed">
              <Send className="w-3 h-3" /> Send for Review
            </button>
          </>
        )}
      </div>

      {/* Security info */}
      <div className="p-4 rounded-xl border border-white/6 bg-white/2">
        <div className="flex items-center gap-2 mb-3">
          <Lock className="w-3.5 h-3.5 text-white/30" />
          <p className="text-white/30 text-[10px] font-bold uppercase tracking-widest">Security & Access</p>
        </div>
        <div className="space-y-2">
          {[
            { label: 'Storage', value: 'AES-256 Encrypted' },
            { label: 'Access', value: 'You + Linked Lawyer' },
            { label: 'Blockchain', value: 'Immutable audit trail' },
            { label: 'Compliance', value: 'Data Protection Act 2019' },
          ].map(({ label, value }, i) => (
            <div key={i} className="flex justify-between items-center">
              <span className="text-white/25 text-[11px]">{label}</span>
              <span className="text-white/50 text-[11px] font-semibold">{value}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Danger */}
      <button className="w-full py-2.5 rounded-xl border border-red-500/15 bg-red-500/4 text-red-400/70 hover:text-red-400 hover:border-red-500/25 text-xs font-bold transition-all flex items-center justify-center gap-2">
        <Trash2 className="w-3.5 h-3.5" /> Delete Document
      </button>
    </div>
  );
}

/* ─────────────────────────────────────────────
   DETAIL PANEL
───────────────────────────────────────────── */
function DetailPanel({ doc, onClose }) {
  const [tab, setTab] = useState('overview');

  const tabs = [
    { id: 'overview', label: 'Overview', icon: FileText },
    { id: 'ai', label: 'AI Analysis', icon: Brain },
    { id: 'signatures', label: 'Signatures', icon: PenTool },
    { id: 'versions', label: 'Versions', icon: History },
    { id: 'actions', label: 'Actions', icon: Zap },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, x: 40 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 40 }}
      transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
      className="flex flex-col h-full overflow-hidden"
    >
      {/* Panel header */}
      <div className="px-5 pt-5 pb-4 border-b border-white/6 flex-shrink-0">
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-center gap-3">
            <div className="text-2xl">{typeIcon(doc.type)}</div>
            <div>
              <h3 className="text-white font-bold text-sm leading-snug line-clamp-2 max-w-[220px]">{doc.title}</h3>
              <div className="flex items-center gap-2 mt-1">
                <StatusBadge status={doc.status} />
              </div>
            </div>
          </div>
          <button onClick={onClose} className="w-7 h-7 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center flex-shrink-0 transition-colors mt-0.5">
            <X className="w-4 h-4 text-white/40" />
          </button>
        </div>

        {/* Linked case */}
        {doc.caseName && (
          <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-white/3 border border-white/6">
            <Link2 className="w-3 h-3 text-[#D4AF37]" />
            <span className="text-white/40 text-[11px]">Linked to</span>
            <span className="text-[#D4AF37] text-[11px] font-semibold truncate">{doc.caseId} — {doc.caseName}</span>
            <ChevronRight className="w-3 h-3 text-white/20 ml-auto flex-shrink-0" />
          </div>
        )}
      </div>

      {/* Tabs */}
      <div className="flex gap-0.5 px-3 py-3 border-b border-white/5 flex-shrink-0 overflow-x-auto">
        {tabs.map(({ id, label, icon: Icon }) => (
          <button key={id} onClick={() => setTab(id)}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-semibold whitespace-nowrap transition-all ${
              tab === id ? 'bg-[#D4AF37]/15 text-[#D4AF37] border border-[#D4AF37]/25' : 'text-white/30 hover:text-white/55 hover:bg-white/4'
            }`}>
            <Icon className="w-3 h-3" /> {label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div className="flex-1 overflow-y-auto px-5 py-5">
        <AnimatePresence mode="wait">
          <motion.div key={tab} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }}>
            {tab === 'overview' && <TabOverview doc={doc} />}
            {tab === 'ai' && <TabAI doc={doc} />}
            {tab === 'signatures' && <TabSignatures doc={doc} />}
            {tab === 'versions' && <TabVersions doc={doc} />}
            {tab === 'actions' && <TabActions doc={doc} onClose={onClose} />}
          </motion.div>
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────
   UPLOAD MODAL
───────────────────────────────────────────── */
function UploadModal({ onClose }) {
  const [dragging, setDragging] = useState(false);

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4"
      onClick={onClose}>
      <motion.div initial={{ scale: 0.92, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.92, opacity: 0 }}
        onClick={e => e.stopPropagation()}
        className="w-full max-w-md rounded-3xl border border-white/8 bg-[#1a1d2e] p-7 shadow-2xl">
        <div className="flex items-center justify-between mb-5">
          <h3 className="text-white font-bold text-lg">Upload Document</h3>
          <button onClick={onClose} className="text-white/30 hover:text-white/60"><X className="w-5 h-5" /></button>
        </div>

        <div
          onDragOver={e => { e.preventDefault(); setDragging(true); }}
          onDragLeave={() => setDragging(false)}
          onDrop={e => { e.preventDefault(); setDragging(false); }}
          className={`border-2 border-dashed rounded-2xl p-10 text-center transition-all cursor-pointer ${
            dragging ? 'border-[#D4AF37]/50 bg-[#D4AF37]/5' : 'border-white/12 hover:border-white/20 hover:bg-white/3'
          }`}>
          <UploadCloud className={`w-10 h-10 mx-auto mb-3 ${dragging ? 'text-[#D4AF37]' : 'text-white/20'}`} />
          <p className="text-white/60 font-semibold mb-1">Drop files here or click to browse</p>
          <p className="text-white/25 text-xs">PDF, DOCX, JPG, PNG up to 25MB</p>
        </div>

        <div className="mt-4 space-y-2">
          <select className="w-full px-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white/60 text-sm outline-none">
            <option value="">Select document type…</option>
            {['Contract', 'Agreement', 'Court Document', 'Evidence', 'Personal Document'].map(t => (
              <option key={t}>{t}</option>
            ))}
          </select>
          <select className="w-full px-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white/60 text-sm outline-none">
            <option value="">Link to case (optional)…</option>
            {MOCK_DOCS.filter(d => d.caseId).map(d => (
              <option key={d.caseId}>{d.caseId} — {d.caseName}</option>
            ))}
          </select>
        </div>

        <div className="flex gap-3 mt-5">
          <button onClick={onClose} className="flex-1 py-3 rounded-xl bg-white/5 border border-white/8 text-white/40 text-sm font-semibold">Cancel</button>
          <button className="flex-1 py-3 rounded-xl bg-[#D4AF37] hover:bg-[#c9a430] text-[#12141f] text-sm font-black transition-all">Upload</button>
        </div>
      </motion.div>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────
   GENERATE MODAL
───────────────────────────────────────────── */
const GEN_TEMPLATES = [
  { icon: '📋', name: 'Employment Contract', credits: 50, time: '2 min', desc: 'Full Kenyan-law compliant employment agreement' },
  { icon: '🤝', name: 'Sale Agreement', credits: 60, time: '2 min', desc: 'Land/property or goods sale agreement' },
  { icon: '📝', name: 'Demand Letter', credits: 20, time: '45 sec', desc: 'Debt recovery or breach of contract demand' },
  { icon: '🏠', name: 'Tenancy Agreement', credits: 40, time: '1.5 min', desc: 'Residential or commercial lease' },
  { icon: '⚖️', name: 'Affidavit', credits: 25, time: '1 min', desc: 'Sworn statutory declaration' },
  { icon: '🛡️', name: 'NDA', credits: 30, time: '1 min', desc: 'Non-disclosure/confidentiality agreement' },
  { icon: '📜', name: 'Power of Attorney', credits: 45, time: '2 min', desc: 'General or specific power of attorney' },
  { icon: '💼', name: 'Partnership Deed', credits: 70, time: '3 min', desc: 'Business partnership agreement' },
];

function GenerateModal({ onClose, onGenerate }) {
  const [selected, setSelected] = useState(null);
  const [step, setStep] = useState(1);
  const [notes, setNotes] = useState('');

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4"
      onClick={onClose}>
      <motion.div initial={{ scale: 0.92, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.92, opacity: 0 }}
        onClick={e => e.stopPropagation()}
        className="w-full max-w-2xl rounded-3xl border border-white/8 bg-[#1a1d2e] shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="px-7 py-5 border-b border-white/6 flex items-center justify-between">
          <div>
            <h3 className="text-white font-bold text-lg flex items-center gap-2"><Brain className="w-5 h-5 text-[#D4AF37]" /> AI Document Generator</h3>
            <p className="text-white/30 text-xs mt-0.5">Kenyan-law compliant · Under 3 minutes · Downloadable PDF</p>
          </div>
          <button onClick={onClose} className="text-white/30 hover:text-white/60"><X className="w-5 h-5" /></button>
        </div>

        <div className="p-7">
          {step === 1 && (
            <>
              <p className="text-white/40 text-sm mb-4">Choose a document template:</p>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5">
                {GEN_TEMPLATES.map((t, i) => (
                  <button key={i} onClick={() => setSelected(t)}
                    className={`p-4 rounded-2xl border text-left transition-all ${
                      selected?.name === t.name ? 'border-[#D4AF37]/40 bg-[#D4AF37]/8' : 'border-white/6 bg-white/3 hover:border-white/12 hover:bg-white/5'
                    }`}>
                    <div className="text-2xl mb-2">{t.icon}</div>
                    <p className="text-white font-bold text-xs mb-1">{t.name}</p>
                    <div className="flex items-center gap-1.5">
                      <Zap className="w-2.5 h-2.5 text-[#D4AF37]" />
                      <span className="text-[#D4AF37] text-[10px] font-bold">{t.credits}</span>
                      <span className="text-white/20 text-[10px]">· {t.time}</span>
                    </div>
                  </button>
                ))}
              </div>
              <div className="flex gap-3">
                <button onClick={onClose} className="flex-1 py-3 rounded-xl bg-white/5 border border-white/8 text-white/40 text-sm font-semibold">Cancel</button>
                <button disabled={!selected} onClick={() => setStep(2)}
                  className="flex-1 py-3 rounded-xl bg-[#D4AF37] disabled:opacity-30 hover:bg-[#c9a430] text-[#12141f] text-sm font-black transition-all flex items-center justify-center gap-2 disabled:cursor-not-allowed">
                  Continue <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </>
          )}

          {step === 2 && selected && (
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
              <div className="flex items-center gap-3 p-4 rounded-xl bg-[#D4AF37]/6 border border-[#D4AF37]/15 mb-5">
                <span className="text-3xl">{selected.icon}</span>
                <div>
                  <p className="text-white font-bold">{selected.name}</p>
                  <p className="text-white/35 text-xs">{selected.desc}</p>
                </div>
              </div>
              <div className="space-y-3 mb-5">
                <div>
                  <label className="text-white/35 text-xs mb-1.5 block">Link to Case (optional)</label>
                  <select className="w-full px-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white/60 text-sm outline-none focus:border-[#D4AF37]/40 transition-colors">
                    <option value="">None</option>
                    {MOCK_DOCS.filter(d => d.caseId).map(d => <option key={d.caseId}>{d.caseId} — {d.caseName}</option>)}
                  </select>
                </div>
                <div>
                  <label className="text-white/35 text-xs mb-1.5 block">AI Instructions (the more detail, the better)</label>
                  <textarea rows={4} value={notes} onChange={e => setNotes(e.target.value)}
                    placeholder={`e.g. "Employment contract for a Software Engineer, salary KES 120,000/month, 6-month probation, non-compete for 1 year, commencing June 2026..."`}
                    className="w-full px-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white/70 text-sm outline-none resize-none placeholder:text-white/20 focus:border-[#D4AF37]/40 transition-colors" />
                </div>
              </div>
              <div className="flex items-center justify-between p-3 rounded-xl bg-[#D4AF37]/6 border border-[#D4AF37]/15 mb-4">
                <div className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-[#D4AF37]" />
                  <span className="text-[#D4AF37] font-bold text-sm">{selected.credits} credits</span>
                  <span className="text-white/25 text-xs">will be deducted</span>
                </div>
                <span className="text-white/25 text-xs flex items-center gap-1"><Clock className="w-3 h-3" /> ~{selected.time}</span>
              </div>
              <div className="flex gap-3">
                <button onClick={() => setStep(1)} className="flex-1 py-3 rounded-xl bg-white/5 border border-white/8 text-white/40 text-sm font-semibold">Back</button>
                <button onClick={() => { onGenerate(selected); onClose(); }}
                  className="flex-1 py-3 rounded-xl bg-[#D4AF37] hover:bg-[#c9a430] text-[#12141f] text-sm font-black transition-all flex items-center justify-center gap-2">
                  <Brain className="w-4 h-4" /> Generate Document
                </button>
              </div>
            </motion.div>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────
   NOTIFICATION TOAST
───────────────────────────────────────────── */
function Toast({ msg, type = 'success', onClose }) {
  useEffect(() => { const t = setTimeout(onClose, 5000); return () => clearTimeout(t); }, []);
  const cfgs = {
    success: { icon: CheckCircle, color: 'text-green-400', bg: 'bg-green-500/8 border-green-500/20' },
    loading: { icon: Loader, color: 'text-[#D4AF37]', bg: 'bg-[#D4AF37]/6 border-[#D4AF37]/20', spin: true },
    error: { icon: AlertCircle, color: 'text-red-400', bg: 'bg-red-500/8 border-red-500/20' },
  };
  const cfg = cfgs[type];
  const Icon = cfg.icon;
  return (
    <motion.div initial={{ opacity: 0, y: -10, x: '-50%' }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}
      className={`fixed top-5 left-1/2 z-[100] flex items-center gap-3 px-5 py-3 rounded-2xl border shadow-2xl shadow-black/50 ${cfg.bg}`}
      style={{ minWidth: 280, maxWidth: 480 }}>
      <Icon className={`w-4 h-4 flex-shrink-0 ${cfg.color} ${cfg.spin ? 'animate-spin' : ''}`} />
      <span className={`text-sm font-semibold ${cfg.color}`}>{msg}</span>
      <button onClick={onClose} className="ml-auto text-white/20 hover:text-white/50"><X className="w-4 h-4" /></button>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────
   MAIN DOCUMENTS VIEW
───────────────────────────────────────────── */
export default function DocumentsView() {
  const [docs] = useState(MOCK_DOCS);
  const [selectedId, setSelectedId] = useState(null);
  const [viewMode, setViewMode] = useState('grid'); // 'grid' | 'table'
  const [search, setSearch] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('All');
  const [statusFilter, setStatusFilter] = useState('all');
  const [sourceFilter, setSourceFilter] = useState('All');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [uploadModal, setUploadModal] = useState(false);
  const [generateModal, setGenerateModal] = useState(false);
  const [toast, setToast] = useState(null);
  const [notifications] = useState([
    { id: 1, msg: 'Land Sale Agreement awaiting your signature', type: 'warning', unread: true },
    { id: 2, msg: 'Affidavit of Service flagged by AI — needs attention', type: 'error', unread: true },
  ]);
  const [notifOpen, setNotifOpen] = useState(false);

  const selectedDoc = docs.find(d => d.id === selectedId) || null;

  const filtered = docs.filter(d => {
    const q = search.toLowerCase();
    const matchSearch = !q || d.title.toLowerCase().includes(q) || d.type.toLowerCase().includes(q) || (d.caseId || '').toLowerCase().includes(q) || (d.caseName || '').toLowerCase().includes(q);
    const matchCat = categoryFilter === 'all' || d.category === categoryFilter;
    const matchType = typeFilter === 'All' || d.type === typeFilter;
    const matchStatus = statusFilter === 'all' || d.status === statusFilter;
    const matchSource = sourceFilter === 'All' || d.source === sourceFilter;
    return matchSearch && matchCat && matchType && matchStatus && matchSource;
  });

  const handleGenerate = (tpl) => {
    setToast({ msg: `Generating "${tpl.name}" using Kenya Law corpus…`, type: 'loading' });
    setTimeout(() => setToast({ msg: `"${tpl.name}" generated! Ready to download.`, type: 'success' }), 3500);
  };

  const needsAttentionCount = docs.filter(d => d.status === 'needs-attention' || d.status === 'pending').length;

  return (
    <div className="min-h-screen bg-[#12141f] text-white font-sans" style={{ fontFamily: "'DM Sans', system-ui, sans-serif" }}>
      {/* Ambient glows */}
      <div className="fixed top-0 left-1/4 w-96 h-96 rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle, rgba(212,175,55,0.04) 0%, transparent 70%)', filter: 'blur(60px)' }} />
      <div className="fixed bottom-0 right-1/4 w-80 h-80 rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle, rgba(99,102,241,0.04) 0%, transparent 70%)', filter: 'blur(60px)' }} />

      {/* Toast */}
      <AnimatePresence>
        {toast && <Toast key={toast.msg} msg={toast.msg} type={toast.type} onClose={() => setToast(null)} />}
      </AnimatePresence>

      {/* Modals */}
      <AnimatePresence>
        {uploadModal && <UploadModal onClose={() => setUploadModal(false)} />}
        {generateModal && <GenerateModal onClose={() => setGenerateModal(false)} onGenerate={handleGenerate} />}
      </AnimatePresence>

      <div className="max-w-[1600px] mx-auto px-4 py-6 flex gap-5 min-h-screen">

        {/* ── LEFT SIDEBAR ── */}
        <aside className="w-52 flex-shrink-0 hidden lg:flex flex-col gap-4 pt-1">
          {/* Categories */}
          <div>
            <p className="text-[10px] text-white/20 uppercase tracking-widest font-bold mb-2 px-2">Categories</p>
            <div className="space-y-0.5">
              {CATEGORIES.map(({ id, label, icon: Icon, count }) => (
                <button key={id} onClick={() => setCategoryFilter(id)}
                  className={`w-full flex items-center gap-2.5 px-3 py-2 rounded-xl text-sm transition-all ${
                    categoryFilter === id
                      ? 'bg-[#D4AF37]/10 border border-[#D4AF37]/20 text-[#D4AF37]'
                      : 'text-white/35 hover:text-white/60 hover:bg-white/4'
                  }`}>
                  <Icon className="w-3.5 h-3.5" />
                  <span className="flex-1 text-left font-medium text-xs">{label}</span>
                  <span className={`text-[10px] font-black ${categoryFilter === id ? 'text-[#D4AF37]/60' : 'text-white/20'}`}>{count}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Folders */}
          <div>
            <div className="flex items-center justify-between mb-2 px-2">
              <p className="text-[10px] text-white/20 uppercase tracking-widest font-bold">Folders</p>
              <button className="text-white/20 hover:text-white/50"><Plus className="w-3 h-3" /></button>
            </div>
            {['Case Documents', 'Templates', 'Signed Copies'].map((f, i) => (
              <button key={i} className="w-full flex items-center gap-2.5 px-3 py-2 rounded-xl text-xs text-white/30 hover:text-white/55 hover:bg-white/4 transition-all">
                <FolderOpen className="w-3.5 h-3.5" /> {f}
              </button>
            ))}
          </div>

          {/* Storage indicator */}
          <div className="mt-auto p-3 rounded-xl border border-white/6 bg-white/2">
            <div className="flex justify-between mb-1.5">
              <span className="text-white/30 text-[10px]">Storage used</span>
              <span className="text-white/50 text-[10px] font-bold">734 KB / 5 GB</span>
            </div>
            <div className="h-1 rounded-full bg-white/6 overflow-hidden">
              <div className="h-full w-[2%] rounded-full bg-[#D4AF37]" />
            </div>
          </div>
        </aside>

        {/* ── MAIN CONTENT ── */}
        <main className="flex-1 min-w-0 flex flex-col gap-4">

          {/* Page header */}
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-white font-black text-2xl tracking-tight">Documents</h1>
              <p className="text-white/25 text-xs mt-0.5">{docs.length} documents · {docs.filter(d => d.status === 'draft').length} drafts · {needsAttentionCount} need attention</p>
            </div>
            <div className="flex items-center gap-2">
              {/* Notifications */}
              <div className="relative">
                <button onClick={() => setNotifOpen(v => !v)}
                  className="relative w-9 h-9 rounded-xl bg-white/5 border border-white/8 flex items-center justify-center hover:bg-white/8 transition-colors">
                  <Bell className="w-4 h-4 text-white/40" />
                  {notifications.some(n => n.unread) && (
                    <span className="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-red-400" />
                  )}
                </button>
                <AnimatePresence>
                  {notifOpen && (
                    <motion.div initial={{ opacity: 0, y: 6, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 6 }}
                      className="absolute right-0 top-full mt-2 w-72 rounded-2xl border border-white/8 bg-[#1a1d2e] shadow-2xl z-30 overflow-hidden">
                      <div className="px-4 py-3 border-b border-white/5 flex items-center justify-between">
                        <p className="text-white/60 text-xs font-bold uppercase tracking-widest">Notifications</p>
                        <button onClick={() => setNotifOpen(false)}><X className="w-3.5 h-3.5 text-white/30" /></button>
                      </div>
                      {notifications.map(n => (
                        <div key={n.id} className="flex items-start gap-3 px-4 py-3 border-b border-white/4 last:border-0 hover:bg-white/3 transition-colors cursor-pointer">
                          <AlertCircle className={`w-4 h-4 mt-0.5 flex-shrink-0 ${n.type === 'error' ? 'text-red-400' : 'text-amber-400'}`} />
                          <p className="text-white/65 text-xs leading-relaxed">{n.msg}</p>
                        </div>
                      ))}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>

              <button onClick={() => setUploadModal(true)}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-white/8 bg-white/4 hover:bg-white/8 text-white/60 hover:text-white text-sm font-semibold transition-all">
                <UploadCloud className="w-4 h-4" /> Upload
              </button>
              <button onClick={() => setGenerateModal(true)}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#D4AF37] hover:bg-[#c9a430] text-[#12141f] text-sm font-black transition-all shadow-lg shadow-[#D4AF37]/15">
                <Brain className="w-4 h-4" /> Generate
              </button>
            </div>
          </div>

          {/* AI Bar */}
          <AIBar doc={selectedDoc} />

          {/* Search + Filter bar */}
          <div className="flex gap-3 flex-wrap">
            <div className="flex-1 min-w-48 relative">
              <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-white/25" />
              <input
                value={search}
                onChange={e => setSearch(e.target.value)}
                placeholder="Search by name, keyword, case, lawyer…"
                className="w-full pl-10 pr-4 py-2.5 rounded-xl bg-white/4 border border-white/8 text-white/80 text-sm outline-none placeholder:text-white/20 focus:border-[#D4AF37]/30 focus:bg-white/5 transition-all"
              />
              {search && (
                <button onClick={() => setSearch('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-white/20 hover:text-white/50">
                  <X className="w-3.5 h-3.5" />
                </button>
              )}
            </div>

            {/* Filter toggle */}
            <button onClick={() => setFiltersOpen(v => !v)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm font-semibold transition-all ${
                filtersOpen ? 'border-[#D4AF37]/30 bg-[#D4AF37]/8 text-[#D4AF37]' : 'border-white/8 bg-white/4 text-white/40 hover:text-white/60'
              }`}>
              <Filter className="w-3.5 h-3.5" /> Filters
              {(typeFilter !== 'All' || statusFilter !== 'all' || sourceFilter !== 'All') && (
                <span className="w-4 h-4 rounded-full bg-[#D4AF37] text-[#12141f] text-[9px] font-black flex items-center justify-center">!</span>
              )}
            </button>

            {/* View mode */}
            <div className="flex gap-0.5 p-1 rounded-xl bg-white/4 border border-white/8">
              <button onClick={() => setViewMode('grid')} className={`p-1.5 rounded-lg transition-all ${viewMode === 'grid' ? 'bg-white/10 text-white' : 'text-white/25 hover:text-white/50'}`}>
                <Grid3x3 className="w-4 h-4" />
              </button>
              <button onClick={() => setViewMode('table')} className={`p-1.5 rounded-lg transition-all ${viewMode === 'table' ? 'bg-white/10 text-white' : 'text-white/25 hover:text-white/50'}`}>
                <List className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Expanded filters */}
          <AnimatePresence>
            {filtersOpen && (
              <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
                className="overflow-hidden">
                <div className="flex flex-wrap gap-4 p-4 rounded-2xl border border-white/6 bg-white/2">
                  {[
                    { label: 'Type', options: DOC_TYPES, value: typeFilter, set: setTypeFilter },
                    { label: 'Source', options: SOURCES, value: sourceFilter, set: setSourceFilter },
                    { label: 'Status', options: STATUSES, value: statusFilter, set: setStatusFilter },
                  ].map(({ label, options, value, set }) => (
                    <div key={label}>
                      <p className="text-[10px] text-white/20 uppercase tracking-widest font-bold mb-2">{label}</p>
                      <div className="flex flex-wrap gap-1.5">
                        {options.map(o => (
                          <button key={o} onClick={() => set(o)}
                            className={`px-3 py-1 rounded-full text-[11px] font-semibold border transition-all capitalize ${
                              value === o ? 'border-[#D4AF37]/30 bg-[#D4AF37]/10 text-[#D4AF37]' : 'border-white/8 bg-white/4 text-white/35 hover:border-white/15 hover:text-white/55'
                            }`}>{o}</button>
                        ))}
                      </div>
                    </div>
                  ))}
                  <button onClick={() => { setTypeFilter('All'); setStatusFilter('all'); setSourceFilter('All'); }}
                    className="self-end ml-auto flex items-center gap-1 text-[11px] text-white/25 hover:text-white/50 transition-colors">
                    <X className="w-3 h-3" /> Clear all
                  </button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Results count */}
          <div className="flex items-center justify-between">
            <p className="text-white/25 text-xs">{filtered.length} document{filtered.length !== 1 ? 's' : ''} found</p>
            {selectedDoc && (
              <button onClick={() => setSelectedId(null)} className="flex items-center gap-1.5 text-xs text-[#D4AF37]/70 hover:text-[#D4AF37] transition-colors">
                <PanelRightClose className="w-3.5 h-3.5" /> Close detail
              </button>
            )}
          </div>

          {/* Document list */}
          {filtered.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <FileText className="w-12 h-12 text-white/10 mb-4" />
              <p className="text-white/30 font-semibold">No documents match your search</p>
              <p className="text-white/15 text-sm mt-1">Try adjusting filters or search query</p>
              <button onClick={() => { setSearch(''); setTypeFilter('All'); setStatusFilter('all'); setSourceFilter('All'); setCategoryFilter('all'); }}
                className="mt-4 px-4 py-2 rounded-xl border border-white/8 text-white/30 hover:text-white/60 text-sm transition-colors">
                Clear all filters
              </button>
            </div>
          ) : viewMode === 'grid' ? (
            <motion.div layout className={`grid gap-4 ${selectedDoc ? 'grid-cols-1 sm:grid-cols-2' : 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3'}`}>
              <AnimatePresence>
                {filtered.map(doc => (
                  <DocCard key={doc.id} doc={doc} selected={selectedId === doc.id} onClick={() => setSelectedId(selectedId === doc.id ? null : doc.id)} />
                ))}
              </AnimatePresence>
            </motion.div>
          ) : (
            <div className="space-y-1">
              {/* Table header */}
              <div className="flex items-center gap-4 px-5 py-2 text-[10px] text-white/20 uppercase tracking-widest font-bold">
                <div className="w-8" />
                <div className="flex-1">Document</div>
                <div className="w-24 hidden sm:block">Source</div>
                <div className="w-28">Status</div>
                <div className="w-16 hidden lg:block">Score</div>
                <div className="w-20 hidden md:block">Updated</div>
                <div className="w-20">Actions</div>
              </div>
              <AnimatePresence>
                {filtered.map(doc => (
                  <DocRow key={doc.id} doc={doc} selected={selectedId === doc.id} onClick={() => setSelectedId(selectedId === doc.id ? null : doc.id)} />
                ))}
              </AnimatePresence>
            </div>
          )}
        </main>

        {/* ── RIGHT DETAIL PANEL ── */}
        <AnimatePresence>
          {selectedDoc && (
            <motion.aside
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 360, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
              className="flex-shrink-0 overflow-hidden rounded-2xl border border-white/6 bg-[#1a1d2e] relative"
              style={{ minHeight: 'calc(100vh - 3rem)', maxHeight: 'calc(100vh - 3rem)', position: 'sticky', top: '1.5rem' }}
            >
              <DetailPanel doc={selectedDoc} onClose={() => setSelectedId(null)} />
            </motion.aside>
          )}
        </AnimatePresence>

      </div>
    </div>
  );
}